name: 'Action Pulsar Dependency Tester'
description: 'Test changes in Core Dependencies of Pulsar'
author: confused-Techie
branding:
  icon: check-square
  color: purple
runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt install -y libnotify4
        curl -L "https://download.pulsar-edit.dev/?os=linux&type=linux_deb" --output pulsar.deb
        sudo dpkg -i pulsar.deb

        pulsar -v
    - if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -L "https://download.pulsar-edit.dev/?os=intel_mac&type=mac_dmg" --output pulsar.dmg
        hdiutil attach pulsar.dmg
        sudo cp -rf /Volumes/Pulsar*/Pulsar.app /Applications
        sudo mkdir -p /usr/local/bin/
        sudo ln -s /Applications/Pulsar.app/Contents/Resources/pulsar.sh /usr/local/bin/pulsar
        #sudo ln -s /Applications/Pulsar.app/Contents/Resources/app/ppm/bin/apm /usr/local/bin/ppm

        pulsar -v
    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $wc = New-Object System.Net.WebClient
        $url = "https://download.pulsar-edit.dev/?os=windows&type=windows_setup"
        $downloadPath = "pulsarInstall.exe"

        Write-Host "Downloading Pulsar to $downloadPath"
        $wc.DownloadFile($url, $downloadPath)

        Write-Host "Installing Pulsar - this may take awhile"
        Start-Process -FilePath $downloadPath -ArgumentList '/currentuser', '/S' -Wait
        Write-Host "Pulsar Install completed"

        Write-Host "Adding Pulsar and PPM directories to GITHUB_PATH"

        "$env:LOCALAPPDATA\Programs\Pulsar\" >> $env:GITHUB_PATH
        "$env:LOCALAPPDATA\Programs\Pulsar\resources\app\ppm\bin\" >> $env:GITHUB_PATH

      - if: runner.os == 'Windows'
        shell: pwsh
        run: |
          pulsar -v
